#!/usr/bin/env python3
# Embeds assets/thumbnails/thumb_NN.bmp as C byte arrays, so the SDL3/SDL2
# ports can load them straight out of the exe's own .rodata instead of
# reading loose files off disk at runtime (see sdlBackend.c's own
# thumbnailsProbeIfNeeded()/gThumbnailBlobs) - a direct, near-verbatim port
# of the sibling Tinyjoypad_SDL project's own tools/gen_thumbnails.py of
# the same name/purpose. Re-run this whenever a thumbnail .bmp is added,
# removed, or regenerated - thumbnailData.h is generated output, not meant
# to be hand-edited.
#
# assets/thumbnails/thumb_NN.bmp are themselves a real, deliberate crop +
# point-sample (NOT blurred/smoothed - this is crisp pixel art) of this
# project's own real captured gameplay screenshots
# (metadata/screenshots/<TITLE>.bmp, produced by `-ms`) down to
# MD_THUMBNAIL_WIDTH x MD_THUMBNAIL_HEIGHT (256x128, machineDependent.h),
# cropped to the real LCD sub-rectangle within each 640x360 capture
# (588x336 at pixel offset (26,12) - GAME_SCALE=7 * LCD_WIDTH=84/
# LCD_HEIGHT=48, see sdlBackend.c's own GAME_SCALE/GAME_ORIGIN_X/_Y) - in
# real registration order (menuGameList.c's own addGame() call sequence),
# NOT alphabetical display order, matching md_drawGameThumbnail()'s own
# real registration-index contract. That crop/downscale step has no
# checked-in generator of its own, matching the sibling Tinyjoypad_SDL
# project's own identical precedent (its own assets/thumbnails/thumb_NN.bmp
# are likewise just checked-in output, not regenerated by any script) - if
# a thumbnail ever needs to be recaptured, redo the crop by hand (see the
# LCD sub-rectangle numbers above) and drop the new thumb_NN.bmp in before
# re-running this script.
#
# Usage: python tools/gen_thumbnails.py

import pathlib

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
THUMB_DIR = REPO_ROOT / "assets" / "thumbnails"
OUT_PATH = THUMB_DIR / "thumbnailData.h"
BYTES_PER_LINE = 20


def format_bytes(data: bytes) -> str:
    lines = []
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i:i + BYTES_PER_LINE]
        lines.append("    " + ",".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def main() -> None:
    # Probe thumb_00.bmp, thumb_01.bmp, ... sequentially, stopping at the
    # first missing index - mirrors the same probe-and-stop convention
    # thumbnailsProbeIfNeeded() uses at runtime, so a future 100th game
    # with no thumbnail yet is still a silent no-op, not an error.
    paths = []
    index = 0
    while True:
        candidate = THUMB_DIR / f"thumb_{index:02d}.bmp"
        if not candidate.exists():
            break
        paths.append(candidate)
        index += 1

    if not paths:
        raise SystemExit(f"no thumb_NN.bmp files found in {THUMB_DIR}")

    out = []
    out.append("// GENERATED FILE - do not edit by hand.")
    out.append("// Regenerate with: python tools/gen_thumbnails.py")
    out.append(f"// Source: assets/thumbnails/thumb_00.bmp .. thumb_{len(paths) - 1:02d}.bmp")
    out.append("#pragma once")
    out.append("")

    for i, path in enumerate(paths):
        data = path.read_bytes()
        out.append(f"static const unsigned char gThumbnail{i:02d}Bmp[] = {{")
        out.append(format_bytes(data))
        out.append("};")
        out.append("")

    out.append("typedef struct")
    out.append("{")
    out.append("    const unsigned char* data;")
    out.append("    unsigned int len;")
    out.append("} ThumbnailBlob;")
    out.append("")
    out.append("static const ThumbnailBlob gThumbnailBlobs[] =")
    out.append("{")
    for i, path in enumerate(paths):
        out.append(f"    {{ gThumbnail{i:02d}Bmp, sizeof( gThumbnail{i:02d}Bmp ) }},")
    out.append("};")
    out.append("")
    out.append("static const int gThumbnailBlobCount = sizeof( gThumbnailBlobs ) / sizeof( gThumbnailBlobs[0] );")
    out.append("")

    OUT_PATH.write_text("\n".join(out), encoding="ascii")
    total_bytes = sum(p.stat().st_size for p in paths)
    print(f"wrote {OUT_PATH} ({len(paths)} thumbnails, {total_bytes} bytes source, "
          f"{OUT_PATH.stat().st_size} bytes generated)")


if __name__ == "__main__":
    main()
